name: Test
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16'
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Prettier
        run: npm run prettier:check
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
